const localAffirmations = [
  "You are enough just as you are.",
  "Every breath is a fresh start.",
  "You are capable of amazing things.",
  "You deserve peace.",
  "Your energy is magnetic and healing.",
  "Let go of what you can’t control.",
  "You bring value to this world.",
  "Even small steps move you forward.",
  "You are resilient, not broken.",
  "You have everything you need inside you.",
  "You’re doing better than you think.",
  "It’s okay to rest.",
  "Progress is progress, even if small.",
  "You’re not alone in this.",
  "You bring light to someone’s day.",
  "Peace begins with a breath.",
  "You’ve survived 100% of your worst days.",
  "This moment is yours to own.",
  "You are allowed to feel joy today.",
  "There is strength in your softness.",
  "Your potential to succeed is infinite.",
  "You are braver than you believe.",
  "Good things are coming your way.",
  "You are full of creativity and ideas.",
  "Your kindness makes a difference.",
  "Believe in yourself and all that you are.",
  "You are stronger than your struggles.",
  "You create your own sunshine.",
  "You are worthy of all good things.",
  "Your dreams are valid and possible.",
  "You have the power to change your story.",
  "You radiate love and happiness.",
  "Your smile can light up the room.",
  "You attract positive energy.",
  "Your mistakes do not define you.",
  "You are constantly growing and evolving.",
  "You are proud of how far you’ve come.",
  "You deserve to be happy and healthy.",
  "You are a source of inspiration.",
  "Your heart knows the way.",
  "You make the world a better place.",
  "You are loved beyond measure.",
  "You have a beautiful mind and soul.",
  "Your presence matters.",
  "You can overcome anything.",
  "You are a magnet for miracles.",
  "You deserve rest and relaxation.",
  "You have endless courage within you.",
  "You are open to new adventures.",
  "Your passion fuels your purpose.",
  "You bring joy to those around you.",
  "You are capable of amazing growth.",
  "Your life is full of possibilities.",
  "You are gentle with yourself.",
  "You inspire others by being you.",
  "You are confident and capable.",
  "You are deserving of love and kindness.",
  "Your light shines bright.",
  "You are grounded and peaceful.",
  "You have the strength to keep going.",
  "You are surrounded by love.",
  "You bring balance to your life.",
  "You are full of positive energy.",
  "You trust the journey of life.",
  "You are kind to yourself and others.",
  "You are open to change and growth.",
  "You are creative and resourceful.",
  "You have a beautiful soul.",
  "You are enough just as you are.",
  "Your voice matters.",
  "You are a beacon of hope.",
  "You deserve all good things in life.",
  "You are fearless and determined.",
  "You are capable of great things.",
  "You choose happiness every day.",
  "You are a work in progress and that’s okay.",
  "You are grateful for the little things.",
  "You have the power to make a difference.",
  "You are gentle with your heart.",
  "You are worthy of your dreams.",
  "You attract success and abundance.",
  "You are resilient and brave.",
  "You make a positive impact.",
  "You are surrounded by positive people.",
  "You are calm and centered.",
  "You have the courage to start anew.",
  "You are loved just as you are.",
  "You are creative beyond measure.",
  "You embrace your uniqueness.",
  "You have limitless potential.",
  "You are deserving of happiness and peace.",
  "You are a shining star.",
  "You are proud of who you are.",
  "You have a kind and loving heart.",
  "You are always growing and evolving.",
  "You are filled with hope and optimism.",
  "You are exactly where you need to be."
];

function showRandomAffirmation() {
  const i = Math.floor(Math.random() * localAffirmations.length);
  document.getElementById('affirmation').textContent = localAffirmations[i];
}

showRandomAffirmation();
